### ISSUE TITLE
It's not working for me, is there any log?

### ISSUE THREAD

**Issue by talesam** [vaxilu/x-ui#124]
I've been using V2ray/xray for over 1 year, I've successfully made several configurations in container, I even created a docker-compose for your configuration, everything loaded fine, but it's not working. I opened the specified port, I had it connected, but it doesn't work. I want to know where the logs are stored.

I put Vless+TCP+XTLS
![Captura de tela de 2021-10-30 20-38-32](https://user-images.githubusercontent.com/981368/139561269-8916abb5-7350-409d-9866-5b401d9f3040.png)

My docker-composer:
```
version: "3.9"

services:
  xui:
    image: talesam/x-ui:latest
    container_name: x-ui
    volumes:
      - /home/tales/Docker/X-UI/etc/x-ui:/etc/x-ui
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    expose:
      - 54321
    ports:
      - 8000-8010:8000-8010/tcp
      - 8000-8010:8000-8010/udp
    restart: always
    networks:
      t4l35-net:

networks:
  t4l35-net:
      name: t4l35-net
```
